### PR TITLE
start work on dynamic params

### PR DESCRIPTION
**Pull request by kevindoveton**

### CODE REVIEW

**Comment by kevindoveton** [comment]
@lewisdaly in your description you said that the dynamic params would be passed in through the url, we don't have a url as calls are generally scheduled... Is this what the experience metadata field in `user_enrolment` is for?

**Comment by lewisdaly** [comment]
> @lewisdaly in your description you said that the dynamic params would be passed in through the url, we don't have a url as calls are generally scheduled... Is this what the experience metadata field in `user_enrolment` is for?

Yep, that's it. We basically need a mechanism for attaching metadata to a notification call.

**Comment by kevindoveton** [comment]
> Yep, that's it. We basically need a mechanism for attaching metadata to a notification call.

Is that metadata per enrolment or per call? Are payments always the same amount or do the vary?

**Comment by lewisdaly** [comment]
> @lewisdaly in your description you said that the dynamic params would be passed in through the url, we don't have a url as calls are generally scheduled... Is this what the experience metadata field in `user_enrolment` is for?

Yep, that's it. We basically need a mechanism for attaching metadata to a notification call.

**Comment by lewisdaly** [comment]
> > Yep, that's it. We basically need a mechanism for attaching metadata to a notification call.
> 
> Is that metadata per enrolment or per call? Are payments always the same amount or do the vary?

The payment amounts will vary from one fortnight to another, so a new enrolment has to be made every 2 weeks.

**Pull request merged**
